name: Create or update .env file
description: Create or update .env file with the given key-value pairs
inputs:
  file-name:
    description: "File name of the .env file. Default is .env"
    required: false
    default: ".env"
  directory-path:
    description: "Directory path to create or update the .env file in. Default is root directory"
    required: false
  append:
    description: "Append the key-value pairs to the existing .env file. Default is false"
    required: false
    default: "false"

runs:
  using: "node20"
  main: "dist/index.js"
